name: windows wheels test

on: [workflow_dispatch]

jobs:
  test_window_wheels:
    name: Wheels on windows-latest
    runs-on: windows-latest
    
    steps:
    - name: Checkout library
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
      
    - run: "cd ext && cd uunet && mkdir build && cd build && cmake -G \"Unix Makefiles\" .. && make && cd .. && cd .. && cd .. && move \"ext/uunet/build/libuunet.dll\" \"uunet.dll\" && dir"
    
#    - run: "cd ext && cd uunet && mkdir build && cd build && cmake -G \"Unix Makefiles\" .. && make && make install"
      
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.19.1

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp311-win_amd64
        CIBW_ARCHS_WINDOWS: AMD64
        #CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "pip install delvewheel && delvewheel show {wheel} && delvewheel repair --add-path . -w {dest_dir} {wheel}"

#    - run: cd wheelhouse && dir && Expand-Archive uunet-2.2.dev3-cp311-cp311-win_amd64.whl && cd uunet-2.2.dev3-cp311-cp311-win_amd64 && dir && move ../../uunet.dll  uunet/ && cd .. && Compress-Archive -Force uunet-2.2.dev3-cp311-cp311-win_amd64 uunet-2.2.dev3-cp311-cp311-win_amd64.whl 
    - run: cd wheelhouse && dir &&  move ../uunet.dll uunet/
    
    - run: cd wheelhouse && dir && python -m pip cache purge && python -m pip install uunet-2.2.dev3-cp311-cp311-win_amd64.whl
      
    - run: cd wheelhouse && python -c "import os; os.add_dll_directory('.'); import uunet.multinet as ml ; ml.empty"
      
    - uses: actions/upload-artifact@v4
      if: false
      with:
        name: cibw-wheels-test
        path: wheelhouse/*.whl
        
    
