name: windows wheels test

on: [workflow_dispatch]

jobs:
  test_window_wheels:
    name: Wheels on windows-latest ${{ matrix.py_version }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    
    steps:
    - name: Checkout library
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py_version }}

    - run: python -m pip wheel .

    - run: mkdir wheelhouse && Move-Item uunet*.whl wheelhouse/

#    - run: cd wheelhouse && dir && python -m pip cache purge && python -m pip install uunet-2.2.dev3-cp311-cp311-win_amd64.whl     
#    - run: cd wheelhouse && python -c "import uunet.multinet as ml ; ml.empty()"
      
    - uses: actions/upload-artifact@v4
      if: false
      with:
        name: cibw-wheels-win-${{ matrix.py_version }}
        path: wheelhouse/*.whl
        
    
