name: windows wheels test

on: [workflow_dispatch]

jobs:
  test_window_wheels:
    name: Wheels on windows-latest
    runs-on: windows-latest
    
    steps:
    - name: Checkout library
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

#    - run: mkdir build && cd build && cmake -G "Unix Makefiles" .. && dir && Get-Content Makefile
    
#    - run: cd build && make && dir

#    - run: "cd ext && cd uunet && mkdir build && cd build && cmake -G \"Unix Makefiles\" .. && make && cd .. && cd .. && cd .. && Move-Item \"ext/uunet/build/libuunet.dll\" \"libuunet.dll\" && Copy-Item \"libuunet.dll\" \"uunet.dll\" && dir"
#    - run: "cd ext && cd uunet && mkdir build && cd build && cmake .. && cmake --build . && cd .. && cd .. && cd .. && Move-Item \"ext/uunet/build/libuunet.dll\" \"libuunet.dll\" && dir"

    - run: python -m pip wheel .

    - run: dir && cd build && dir

#    - run: mkdir wheelhouse && dir && Move-Item *.whl wheelhouse/ && dir

#    - run: "cd ext && cd uunet && mkdir build && cd build && cmake -G \"Unix Makefiles\" .. && make && make install"
      
    - name: Install cibuildwheel
      if: false
      run: python -m pip install cibuildwheel==2.19.1

    - name: Build wheels
      if: false
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: cp311-win_amd64
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "dir && pip install delvewheel && delvewheel show -v --add-path . {wheel} && delvewheel repair -v --add-path . -w {dest_dir} {wheel}"

#    - run: cd wheelhouse && dir && Expand-Archive uunet-2.2.dev3-cp311-cp311-win_amd64.whl && cd uunet-2.2.dev3-cp311-cp311-win_amd64 && dir && move ../../uunet.dll  uunet/ && cd .. && Compress-Archive -Force uunet-2.2.dev3-cp311-cp311-win_amd64 uunet-2.2.dev3-cp311-cp311-win_amd64.whl 
#    - run: mkdir wheelhouse && cd wheelhouse && dir &&  Move-Item ../libuunet.dll libuunet.dll && Copy-Item libuunet.dll uunet.dll

# puts repaired in wheelhouse by default
    - run: mkdir wheelhouse && dir && pip install delvewheel && delvewheel show -v --add-path . uunet-2.2.dev3-cp311-cp311-win_amd64.whl && delvewheel repair -v --add-path . uunet-2.2.dev3-cp311-cp311-win_amd64.whl
      if: false
    - run: cd wheelhouse && dir && python -m pip cache purge && python -m pip install uunet-2.2.dev3-cp311-cp311-win_amd64.whl
      if: false
    - run: cd wheelhouse && python -c "import os; wd = os.path.abspath('.'); os.add_dll_directory(wd); import uunet.multinet as ml ; ml.empty"
      if: false
    - uses: actions/upload-artifact@v4
      if: false
      with:
        name: cibw-wheels-test
        path: wheelhouse/*.whl
        
    
